baseURL = "http://example.org/"
languageCode = "fr"
title = "Recettes de cuisine"
theme = "ananke"
DefaultContentLanguage = "fr"

[taxonomies]
    tag = "tags"

[params]
    background_color_class = "bg-dark-gray"
